name: tabler_icons_plus_example
description: Example app showcasing all Tabler Icons.
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  tabler_icons_plus:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
